### ISSUE TITLE
pthis sandbox addon.

### ISSUE THREAD

**Issue by HarlemRiverDrive** [HarlemRiverDrive/Battlefield-2-Sandbox-Addon-Archive#1]
@futureman2007

You were looking for the projectiles addon (pthis) around 4 months ago. I have uploaded it here along with the rest of the sandbox addons I happen to have.

**Comment by futureman2007** [comment]
Nice! Here on git?

**Comment by HarlemRiverDrive** [comment]
@futureman2007
Yes, this is an issue on the repo it is in.

**Comment by futureman2007** [comment]
Wow! Thanks!
